name: Update Silver Price

on:
  schedule:
    - cron: "*/10 * * * *"   # هر 10 دقیقه
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

    - name: Fetch silver price
  env:
    API_KEY: ${{ secrets.GOLDAPIKEY }}
  run: |
    echo "Starting API request..."

    if [ -z "$API_KEY" ]; then
      echo "❌ API KEY EMPTY"
      echo '{"error":"API key missing"}' > silver.json
      exit 0
    fi

    response=$(curl -s -w "HTTPSTATUS:%{http_code}" \
    -H "x-access-token: $API_KEY" \
    https://api.gold-api.com/price/XAG)

    body=$(echo "$response" | sed -e 's/HTTPSTATUS\:.*//g')
    status_code=$(echo "$response" | sed -e 's/.*HTTPSTATUS://')

    echo "Status Code: $status_code"
    echo "Response Body: $body"

    if [ "$status_code" -eq 200 ] && [ -n "$body" ]; then
      echo "$body" > silver.json
    else
      echo "{\"error\":\"API failed\",\"status\":$status_code}" > silver.json
    fi
