name: Update Silver Price

on:
  schedule:
    - cron: "*/10 * * * *"   # هر 10 دقیقه
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch silver price
        run: |
          curl -s -H "x-access-token: ${{ secrets.GOLDAPIKEY }}" \
          https://www.goldapi.io/api/XAG/USD > silver.json

      - name: Show result
        run: cat silver.json

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add silver.json
          git commit -m "update silver price" || echo "No changes"
          git push
